from enum import Enum

class INCOME_STMT_KPI(Enum):
    REVENUE = "Total Revenue"
    COGS = "Operating Expense"
    GROSS_PROFIT = "Gross Profit"
    EBITDA = "EBITDA"
    INTEREST_EXPENSE = "Interest Expense"

class BALANCE_SHEET_KPI(Enum):
    TOTAL_DEPT = "Total Debt"
    CASH = "Cash And Cash Equivalents"
    TOTAL_CAPITALIZATION = "Total Capitalization"

class COMPUTED_KPI(Enum):
    LEVERAGE = "Leverage"
    ENTERPRISE_MULTIPLE = "Enterprise Multiple"
    EBITDA_MARGIN = "EBITDA Margin"
    REVENUE_GROWTH = "Revenue Growth"
    EBITDA_GROWTH = "EBITDA Growth"


ORDERED_KPIS = [
    INCOME_STMT_KPI.REVENUE,
    COMPUTED_KPI.REVENUE_GROWTH,
    INCOME_STMT_KPI.COGS,
    INCOME_STMT_KPI.GROSS_PROFIT,
    INCOME_STMT_KPI.EBITDA,
    COMPUTED_KPI.EBITDA_GROWTH,
    COMPUTED_KPI.EBITDA_MARGIN,
    INCOME_STMT_KPI.INTEREST_EXPENSE,
    BALANCE_SHEET_KPI.TOTAL_DEPT,
    BALANCE_SHEET_KPI.CASH,
    BALANCE_SHEET_KPI.TOTAL_CAPITALIZATION,
    COMPUTED_KPI.LEVERAGE
]
